modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="skycraft"
version="0.1.2-neoforge-alpha.1"
displayName="SkyCraft (NeoForge)"
authors="chasmlol; NeoForge port for AteamPlays"
description='''
Play Skyrim with Minecraft physics, inventory and viewmodels.
NeoForge 1.21.1 compatibility port.
'''

[[dependencies.skycraft]]
modId="neoforge"
type="required"
versionRange="[21.1.252,)"
ordering="NONE"
side="CLIENT"

[[dependencies.skycraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
